import Link from 'next/link';
import { resolveBrandContext, withBrandTransaction } from '../../../lib/brand-context';
import { loadLearningDashboard } from '../../../lib/learning-data';
import styles from '../workspace.module.css';
export const dynamic='force-dynamic';
export default async function LearningPage(){
  const context=await resolveBrandContext();const dashboard=await withBrandTransaction(context,(client)=>loadLearningDashboard(client,context.tenantId));
  if(dashboard.module?.availability!=='ACTIVE')return <><section className={styles.pageHead}><div><p className={styles.eyebrow}>Learning</p><h1>Learning workspace</h1><p>Build courses, enroll learners, assess capability, issue credentials and use governed Learning AI.</p></div></section><div className={styles.notice}><strong>Learning is not active for this tenant.</strong><p>Availability: {dashboard.module?.availability??'UNAVAILABLE'}. Activation never creates an entitlement.</p><Link className={styles.button} href="/learning/settings">Open Learning settings</Link></div></>;
  return <><section className={styles.pageHead}><div><p className={styles.eyebrow}>Learning</p><h1>{dashboard.academyName??'Learning Academy'}</h1><p>One operational view across content, learners, progress and credentials.</p></div><div className={styles.appActions}><Link className={styles.secondaryButton} href="/learning/assignments">Grade assignments</Link><Link className={styles.button} href="/learning/courses">Manage courses</Link></div></section>
  <section className={styles.grid}>{dashboard.metrics.map((metric)=><article key={metric.label} className={styles.metric}><div className={styles.metricLabel}>{metric.label}</div><div className={styles.metricValue}>{metric.value}</div><div className={styles.metricDetail}>{metric.detail}</div></article>)}</section>
  <section className={styles.panel}><div className={styles.panelHead}><h2>Recently updated courses</h2><Link href="/learning/courses">View catalog</Link></div>{dashboard.recentCourses.length===0?<div className={styles.empty}>No courses yet. Create the first course to start the Learning golden path.</div>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Course</th><th>Key</th><th>Published</th><th>Draft</th></tr></thead><tbody>{dashboard.recentCourses.map((course)=><tr key={course.courseId}><td><Link href={`/learning/courses/${course.courseId}`}><strong>{course.draftTitle??course.publishedTitle??course.courseKey}</strong></Link></td><td>{course.courseKey}</td><td>{course.currentPublishedVersion??'—'}</td><td>{course.draftVersion??'—'}</td></tr>)}</tbody></table></div>}</section></>
}
